version: "3.7"

services:
  bing_wallpaper:
    build:
      context: .
      dockerfile: ./Dockerfile # build file
    image: bbonkr/mondaycom_webhooks_app:latest # name of image
    container_name: mondaycom_webhooks_app # name of container
    restart: always
    ports:
      - 5000:5000
    environment:
      - TZ=Asia/Seoul
      - ASPNETCORE_ENVIRONMENT=Production
      - DOTNET_RUNNING_IN_CONTAINER=true
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__Default=<database connection string here>
    network_mode: bridge
